language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t timerdmann/docker-react .

script:
  - docker run -e CI=true timerdmann/docker-react npm run test